'use client';

import { useEffect, useMemo, useState } from 'react';
import type { Session } from '@supabase/supabase-js';
import { supabase } from './lib/supabase';

type Task = { id: number; title: string; meta: string; person: string; tone: string; done: boolean; priority: string };
type View = 'Visão geral' | 'Calendário' | 'Tarefas' | 'Listas' | 'Orçamento' | 'Refeições' | 'Documentos' | 'Mensagens' | 'Localização' | 'Rotinas' | 'Aniversários' | 'Família' | 'Notificações' | 'Assistente' | 'Configurações';

const nav: [string, View][] = [['⌂', 'Visão geral'], ['▣', 'Calendário'], ['✓', 'Tarefas'], ['☷', 'Listas'], ['◔', 'Orçamento'], ['◒', 'Refeições'], ['▤', 'Documentos'], ['✉', 'Mensagens'], ['⌖', 'Localização']];
const moreNav: [string, View][] = [['♧', 'Rotinas'], ['★', 'Aniversários']];
const members = [{ name: 'Você', initials: 'VC', color: '#e8a15a', role: 'Administrador', status: 'Disponível' }, { name: 'Ana', initials: 'AN', color: '#9aa6db', role: 'Adulto', status: 'Disponível' }, { name: 'Pedro', initials: 'PE', color: '#8ec0a7', role: 'Criança', status: 'Na escola' }];
const initialTasks: Task[] = [{ id: 1, title: 'Levar Pedro à natação', meta: 'Hoje · 17:30', person: 'Você', tone: 'orange', done: false, priority: 'Alta' }, { id: 2, title: 'Comprar ração da Amora', meta: 'Hoje · Lista da casa', person: 'Ana', tone: 'lilac', done: false, priority: 'Normal' }, { id: 3, title: 'Separar uniforme da escola', meta: 'Amanhã · Rotina', person: 'Pedro', tone: 'mint', done: true, priority: 'Normal' }];
const initialLists = [{ id: 1, name: 'Compras da semana', items: ['Leite', 'Bananas', 'Café em pó', 'Ração da Amora'], checked: [true, true, false, false] }, { id: 2, name: 'Churrasco de sábado', items: ['Carvão', 'Pão de alho', 'Refrigerante'], checked: [false, false, false] }];

export default function Home() { return <WebAuthGate />; }

function WebAuthGate() {
  const [session, setSession] = useState<Session | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    supabase.auth.getSession().then(({ data }) => { setSession(data.session); setLoading(false); });
    const { data: listener } = supabase.auth.onAuthStateChange((_event, next) => setSession(next));
    return () => listener.subscription.unsubscribe();
  }, []);

  if (loading) return <div className="auth-shell"><div className="auth-card"><span className="brand-mark">n</span><p>Carregando seu Ninho…</p></div></div>;
  if (!session) return <AuthScreen />;
  return <HomeContent session={session} onSignOut={() => supabase.auth.signOut()} />;
}

function AuthScreen() {
  const [mode, setMode] = useState<'signin' | 'signup'>('signin');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');

  async function submit() {
    setMessage('');
    if (!email || !password) return setMessage('Informe e-mail e senha.');
    setBusy(true);
    const result = mode === 'signin'
      ? await supabase.auth.signInWithPassword({ email, password })
      : await supabase.auth.signUp({ email, password });
    setBusy(false);
    if (result.error) setMessage(result.error.message);
    else if (mode === 'signup') setMessage('Conta criada. Confirme seu e-mail para continuar.');
  }

  async function googleLogin() {
    setMessage('');
    const { error } = await supabase.auth.signInWithOAuth({ provider: 'google', options: { redirectTo: window.location.origin } });
    if (error) setMessage(error.message);
  }

  async function recover() {
    if (!email) return setMessage('Informe seu e-mail para receber o link.');
    const { error } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/` });
    setMessage(error ? error.message : 'Enviamos um link de recuperação para seu e-mail.');
  }

  return <main className="auth-shell"><section className="auth-card"><div className="auth-brand"><span className="brand-mark">n</span><strong>Ninho</strong></div><p className="eyebrow">ORGANIZAÇÃO FAMILIAR</p><h1>{mode === 'signin' ? 'Que bom ter você de volta.' : 'Crie seu espaço familiar.'}</h1><p className="auth-copy">Agenda, tarefas e decisões da casa em um só lugar — com seus dados protegidos.</p><button className="social-button" onClick={googleLogin}>Continuar com Google</button><div className="auth-divider"><span>ou continue com e-mail</span></div><label className="auth-label">E-mail<input type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="voce@email.com" /></label><label className="auth-label">Senha<input type="password" autoComplete={mode === 'signin' ? 'current-password' : 'new-password'} value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Sua senha" /></label>{message && <p className="auth-message">{message}</p>}<button className="dark-button auth-submit" disabled={busy} onClick={submit}>{busy ? 'Aguarde…' : mode === 'signin' ? 'Entrar' : 'Criar conta'}</button>{mode === 'signin' && <button className="auth-link" onClick={recover}>Esqueci minha senha</button>}<p className="auth-switch">{mode === 'signin' ? 'Ainda não tem uma conta?' : 'Já tem uma conta?'} <button onClick={() => { setMode(mode === 'signin' ? 'signup' : 'signin'); setMessage(''); }}>{mode === 'signin' ? 'Criar conta' : 'Entrar'}</button></p></section></main>;
}

function HomeContent({ session, onSignOut }: { session: Session; onSignOut: () => void }) {
  const [active, setActive] = useState<View>('Visão geral');
  const [tasks, setTasks] = useState<Task[]>(initialTasks);
  const [lists, setLists] = useState(initialLists);
  const [notice, setNotice] = useState('');
  const [composer, setComposer] = useState('');
  const [assistantText, setAssistantText] = useState('');
  const [assistantPreview, setAssistantPreview] = useState('');
  const [showAll, setShowAll] = useState(false);

  const pending = useMemo(() => tasks.filter((task) => !task.done).length, [tasks]);
  const flash = (text: string) => { setNotice(text); window.setTimeout(() => setNotice(''), 2300); };
  const toggleTask = (id: number) => setTasks((current) => current.map((task) => task.id === id ? { ...task, done: !task.done } : task));
  const addTask = () => { if (!composer.trim()) return; setTasks((current) => [...current, { id: Date.now(), title: composer, meta: 'Hoje · criada agora', person: 'Você', tone: 'orange', done: false, priority: 'Normal' }]); setComposer(''); flash('Tarefa adicionada'); };
  const setView = (view: View) => { setActive(view); setComposer(''); };

  return <main className="app-shell">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark">n</span><span>Ninho</span></div>
      <div className="family-switcher"><span className="family-dot">⌂</span><span><small>Família</small><strong>Casa Oliveira</strong></span><span className="chevron">⌄</span></div>
      <nav className="nav-list" aria-label="Navegação principal">{nav.map(([icon, label]) => <NavButton key={label} icon={icon} label={label} active={active} onClick={setView} />)}</nav>
      <div className="nav-label">Mais do Ninho</div>
      {moreNav.map(([icon, label]) => <NavButton key={label} icon={icon} label={label} active={active} onClick={setView} />)}
      <div className="sidebar-bottom"><NavButton icon="◉" label="Notificações" active={active} onClick={() => setView('Notificações')} badge="3" /><NavButton icon="⚙" label="Configurações" active={active} onClick={() => setView('Configurações')} /><div className="profile-row"><span className="avatar avatar-you">{(session.user.email ?? 'VC').slice(0, 2).toUpperCase()}</span><span><strong>{session.user.email}</strong><small>Conta conectada</small></span><button className="more" aria-label="Sair" onClick={onSignOut}>↪</button></div></div>
    </aside>
    <section className="content">
      <header className="topbar"><div className="mobile-brand"><span className="brand-mark">n</span>Ninho</div><div className="breadcrumbs">Casa Oliveira <span>/</span> {active}</div><div className="top-actions"><button className="icon-button" aria-label="Pesquisar" onClick={() => flash('Busca em todas as áreas')}>⌕</button><button className="help-button" onClick={() => setView('Assistente')}>?</button><button className="invite-button" onClick={() => flash('Link de convite copiado')}>＋ Convidar</button></div></header>
      <div className="page-wrap">{active === 'Visão geral' ? <Dashboard pending={pending} tasks={tasks} toggleTask={toggleTask} setView={setView} showAll={showAll} setShowAll={setShowAll} lists={lists} flash={flash} /> : <ModuleView view={active} tasks={tasks} lists={lists} pending={pending} composer={composer} setComposer={setComposer} addTask={addTask} toggleTask={toggleTask} setView={setView} flash={flash} assistantText={assistantText} setAssistantText={setAssistantText} assistantPreview={assistantPreview} setAssistantPreview={setAssistantPreview} />}</div>
    </section>{notice && <div className="toast">✦ &nbsp; {notice}</div>}
  </main>;
}

function NavButton({ icon, label, active, onClick, badge }: { icon: string; label: View; active: View; onClick: (label: View) => void; badge?: string }) { return <button className={`nav-item ${active === label ? 'selected' : ''}`} onClick={() => onClick(label)}><span className="nav-icon">{icon}</span>{label}{badge && <span className="badge">{badge}</span>}</button>; }

function Dashboard({ pending, tasks, toggleTask, setView, showAll, setShowAll, lists, flash }: { pending: number; tasks: Task[]; toggleTask: (id: number) => void; setView: (view: View) => void; showAll: boolean; setShowAll: (value: boolean) => void; lists: typeof initialLists; flash: (text: string) => void }) { return <>
  <div className="welcome-row"><div><p className="eyebrow">QUINTA-FEIRA, 28 DE AGOSTO</p><h1>Bom dia, Vanessa <span className="wave">✦</span></h1><p className="subcopy">Tudo que a sua família precisa, em um só lugar.</p></div><div className="weather"><span>☀</span><div><strong>24°</strong><small>São Paulo, SP</small></div></div></div>
  <div className="quick-grid"><QuickCard tone="peach" icon="✦" title="Novo evento" subtitle="Adicione à agenda da família" onClick={() => setView('Calendário')} /><QuickCard tone="lavender" icon="✓" title="Nova tarefa" subtitle="Divida o que precisa ser feito" onClick={() => setView('Tarefas')} /><QuickCard tone="mint" icon="◔" title="Lançar despesa" subtitle="Controle o orçamento da casa" onClick={() => setView('Orçamento')} /></div>
  <div className="dashboard-grid"><div className="main-column"><section className="panel agenda-panel"><PanelHeading eyebrow="AGENDA DA FAMÍLIA" title="Próximos compromissos" action="Ver calendário" onClick={() => setView('Calendário')} /><div className="week-strip">{[['SEG','25'],['TER','26'],['QUA','27'],['QUI','28'],['SEX','29'],['SÁB','30'],['DOM','31']].map(([day, date], i) => <button key={day} className={`day ${i === 3 ? 'today' : ''}`}><span>{day}</span><strong>{date}</strong></button>)}</div><div className="event-list"><Event time="09:00" title="Reunião de pais · Escola Monteiro" tag="Vanessa" color="orange" /><Event time="17:30" title="Natação do Pedro" tag="Pedro" color="mint" /><Event time="19:00" title="Jantar em família" tag="Todos" color="lilac" /></div></section><section className="panel tasks-panel"><PanelHeading eyebrow="PARA HOJE" title={<>Tarefas pendentes <span className="count-pill">{pending}</span></>} action={showAll ? 'Mostrar menos' : 'Ver todas'} onClick={() => setShowAll(!showAll)} /><div className="task-list">{tasks.slice(0, showAll ? tasks.length : 3).map((task) => <TaskRow key={task.id} task={task} toggleTask={toggleTask} />)}</div></section></div><aside className="right-column"><FamilyCard setView={setView} /><section className="panel list-panel"><PanelHeading eyebrow="LISTA COMPARTILHADA" title={lists[0].name} action="Abrir lista" onClick={() => setView('Listas')} /><div className="progress-track"><span style={{ width: `${(lists[0].checked.filter(Boolean).length / lists[0].items.length) * 100}%` }} /></div><div className="shopping-list">{lists[0].items.map((item, i) => <label key={item}><input type="checkbox" checked={lists[0].checked[i]} onChange={() => flash('Lista atualizada')} /> <span>{item}</span></label>)}</div></section><section className="assistant-card"><div className="assistant-glow">✦</div><p className="eyebrow">NINHO AJUDA</p><h2>Quer organizar a semana?</h2><p>Posso encontrar espaços na agenda ou dividir as tarefas da casa.</p><button onClick={() => setView('Assistente')}>Conversar com o Ninho <span>→</span></button></section></aside></div>
</>; }

function ModuleView({ view, tasks, lists, pending, composer, setComposer, addTask, toggleTask, setView, flash, assistantText, setAssistantText, assistantPreview, setAssistantPreview }: { view: View; tasks: Task[]; lists: typeof initialLists; pending: number; composer: string; setComposer: (value: string) => void; addTask: () => void; toggleTask: (id: number) => void; setView: (view: View) => void; flash: (text: string) => void; assistantText: string; setAssistantText: (value: string) => void; assistantPreview: string; setAssistantPreview: (value: string) => void }) {
  const titles: Record<string, [string, string]> = { Calendário: ['Sua semana, com mais clareza.', 'Todos os compromissos da família em um só lugar.'], Tarefas: ['O que precisa acontecer.', `${pending} tarefas aguardam atenção hoje.`], Listas: ['Tudo o que a casa precisa.', 'Listas compartilhadas, simples de atualizar.'], Orçamento: ['Dinheiro da casa, sem complicação.', 'Acompanhe receitas, despesas e limites do mês.'], Refeições: ['Comer bem começa no planejamento.', 'Monte a semana e transforme o cardápio em compras.'], Documentos: ['Documentos importantes, protegidos.', 'Encontre informações da família quando precisar.'], Mensagens: ['Conversem no ritmo da família.', 'Recados importantes não se perdem mais.'], Localização: ['Cuidado, com consentimento.', 'Compartilhe localização somente quando fizer sentido.'], Rotinas: ['Pequenos hábitos, mais tranquilidade.', 'Rotinas de filhos, idosos e pets em um só lugar.'], Aniversários: ['Celebre quem importa.', 'Nunca mais deixe uma data especial passar.'], Família: ['A sua rede de cuidado.', 'Gerencie membros, papéis e permissões.'], Notificações: ['Nada importante fica para trás.', 'Convites, lembretes e alterações recentes.'], Assistente: ['Organize com uma conversa.', 'O Ninho propõe ações e pede sua confirmação antes de executar.'], Configurações: ['Seu Ninho, do seu jeito.', 'Privacidade, preferências e assinatura da família.'] };
  const [title, subtitle] = titles[view];
  return <><div className="module-header"><div><p className="eyebrow">{view.toUpperCase()}</p><h1>{title}</h1><p className="subcopy">{subtitle}</p></div><button className="dark-button" onClick={() => flash(`Novo item em ${view}`)}>＋ Adicionar</button></div><div className="module-content">{view === 'Calendário' && <CalendarView setView={setView} />} {view === 'Tarefas' && <TasksView tasks={tasks} toggleTask={toggleTask} composer={composer} setComposer={setComposer} addTask={addTask} />} {view === 'Listas' && <ListsView lists={lists} flash={flash} />} {view === 'Orçamento' && <BudgetView />} {view === 'Refeições' && <MealsView setView={setView} />} {view === 'Documentos' && <SimpleCards type="docs" flash={flash} />} {view === 'Mensagens' && <MessagesView composer={composer} setComposer={setComposer} flash={flash} />} {view === 'Localização' && <LocationView flash={flash} />} {view === 'Rotinas' && <RoutinesView flash={flash} />} {view === 'Aniversários' && <BirthdaysView />} {view === 'Família' && <FamilyView flash={flash} />} {view === 'Notificações' && <NotificationsView />} {view === 'Assistente' && <AssistantView text={assistantText} setText={setAssistantText} preview={assistantPreview} setPreview={setAssistantPreview} flash={flash} />} {view === 'Configurações' && <SettingsView flash={flash} />}</div></>;
}

function PanelHeading({ eyebrow, title, action, onClick }: { eyebrow: string; title: React.ReactNode; action?: string; onClick?: () => void }) { return <div className="panel-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{action && <button className="text-button" onClick={onClick}>{action} <span>→</span></button>}</div>; }
function QuickCard({ tone, icon, title, subtitle, onClick }: { tone: string; icon: string; title: string; subtitle: string; onClick: () => void }) { return <button className={`quick-card ${tone}`} onClick={onClick}><span className="quick-icon">{icon}</span><span><strong>{title}</strong><small>{subtitle}</small></span><span className="arrow">↗</span></button>; }
function TaskRow({ task, toggleTask }: { task: Task; toggleTask: (id: number) => void }) { return <div className={`task-row ${task.done ? 'completed' : ''}`}><button className="check" onClick={() => toggleTask(task.id)} aria-label={`Concluir ${task.title}`}>{task.done ? '✓' : ''}</button><div className="task-copy"><strong>{task.title}</strong><small>{task.meta} · {task.priority}</small></div><span className={`assignee ${task.tone}`}>{task.person === 'Você' ? 'VC' : task.person.slice(0, 2).toUpperCase()}</span></div>; }
function Event({ time, title, tag, color }: { time: string; title: string; tag: string; color: string }) { return <div className="event-row"><span className="event-time">{time}</span><span className={`event-line ${color}`} /><div className="event-title"><strong>{title}</strong><small><span className={`tag-dot ${color}`} /> {tag}</small></div><button className="event-more">•••</button></div>; }
function FamilyCard({ setView }: { setView: (view: View) => void }) { return <section className="panel family-panel"><PanelHeading eyebrow="NA FAMÍLIA" title="Quem está por aqui" action="Gerenciar" onClick={() => setView('Família')} /><div className="members">{members.map((member) => <div className="member" key={member.name}><span className="member-avatar" style={{ background: member.color }}>{member.initials}</span><span><strong>{member.name}</strong><small>{member.status}</small></span><i className={`status ${member.name === 'Pedro' ? 'away' : ''}`} /></div>)}</div><button className="outline-button" onClick={() => setView('Família')}>＋ Adicionar membro</button></section>; }

function CalendarView({ setView }: { setView: (view: View) => void }) { return <div className="calendar-layout"><section className="panel calendar-big"><div className="calendar-toolbar"><button>←</button><strong>Agosto 2026</strong><button>→</button><span className="calendar-spacer" /><button className="filter-button">Todos os membros⌄</button></div><div className="calendar-grid">{['SEG','TER','QUA','QUI','SEX','SÁB','DOM'].map((d) => <span className="calendar-weekday" key={d}>{d}</span>)}{Array.from({ length: 35 }, (_, i) => { const day = i - 5; return <button key={i} className={`calendar-cell ${day === 28 ? 'calendar-today' : ''} ${[1, 2, 8, 15, 22, 29].includes(day) ? 'has-event' : ''}`}>{day > 0 && day < 32 ? <><strong>{day}</strong>{day === 28 && <small>Hoje</small>}{day === 27 && <i className="calendar-dot orange" />}{day === 29 && <i className="calendar-dot mint" />}</> : ''}</button>; })}</div></section><section className="panel side-agenda"><PanelHeading eyebrow="QUI, 28 AGO" title="Agenda do dia" /><Event time="09:00" title="Reunião de pais" tag="Vanessa" color="orange" /><Event time="17:30" title="Natação do Pedro" tag="Pedro" color="mint" /><Event time="19:00" title="Jantar em família" tag="Todos" color="lilac" /><button className="dark-button full" onClick={() => setView('Assistente')}>Encontrar um horário livre</button></section></div>; }
function TasksView({ tasks, toggleTask, composer, setComposer, addTask }: { tasks: Task[]; toggleTask: (id: number) => void; composer: string; setComposer: (value: string) => void; addTask: () => void }) { return <div className="two-col"><section className="panel"><div className="input-row"><input value={composer} onChange={(e) => setComposer(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && addTask()} placeholder="Ex.: marcar consulta do Pedro" /><button className="dark-button" onClick={addTask}>Adicionar tarefa</button></div><div className="task-filters"><button className="active-filter">Todas · {tasks.length}</button><button>Pendentes · {tasks.filter((t) => !t.done).length}</button><button>Concluídas · {tasks.filter((t) => t.done).length}</button></div><div className="task-list large-list">{tasks.map((task) => <TaskRow key={task.id} task={task} toggleTask={toggleTask} />)}</div></section><section className="panel side-summary"><p className="eyebrow">DIVISÃO DA CASA</p><h2>Equilíbrio da semana</h2><div className="bar-stat"><span>Vanessa</span><i><b style={{ width: '72%' }} /></i><strong>6</strong></div><div className="bar-stat"><span>Ana</span><i><b style={{ width: '54%', background: '#9da4d4' }} /></i><strong>4</strong></div><div className="bar-stat"><span>Pedro</span><i><b style={{ width: '27%', background: '#8bb99e' }} /></i><strong>2</strong></div><button className="outline-button">Organizar automaticamente</button></section></div>; }
function ListsView({ lists, flash }: { lists: typeof initialLists; flash: (text: string) => void }) { return <div className="lists-grid">{lists.map((list) => <section className="panel list-card" key={list.id}><div className="list-card-title"><div><p className="eyebrow">LISTA COMPARTILHADA</p><h2>{list.name}</h2></div><span>{list.items.length} itens</span></div><div className="progress-track"><span style={{ width: `${(list.checked.filter(Boolean).length / list.items.length) * 100}%` }} /></div>{list.items.map((item, i) => <label className="shopping-item" key={item}><input type="checkbox" checked={list.checked[i]} onChange={() => flash(`${item} atualizado`)} /><span>{item}</span><small>{i % 2 ? 'Ana' : 'Você'}</small></label>)}<button className="text-button list-add" onClick={() => flash('Item adicionado à lista')}>＋ Adicionar item</button></section>)}<button className="new-list-card" onClick={() => flash('Nova lista criada')}><span>＋</span><strong>Criar nova lista</strong><small>Compras, viagem, mudança...</small></button></div>; }
function BudgetView() { return <div className="budget-view"><div className="metric-grid"><Metric label="Saldo do mês" value="R$ 3.840" note="disponível" tone="peach" /><Metric label="Receitas" value="R$ 8.500" note="+12% vs. mês passado" tone="mint" /><Metric label="Despesas" value="R$ 4.660" note="55% do orçamento" tone="lavender" /></div><div className="two-col"><section className="panel chart-card"><PanelHeading eyebrow="AGOSTO 2026" title="Fluxo do mês" action="Exportar" /><div className="fake-chart"><div className="chart-lines"><span /><span /><span /><span /></div><div className="bars">{[45, 66, 54, 75, 63, 86, 70, 92, 64, 78, 58, 70].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div><div className="chart-months">{['S1','S2','S3','S4'].map((m) => <small key={m}>{m}</small>)}</div></div></section><section className="panel"><PanelHeading eyebrow="POR CATEGORIA" title="Onde o dinheiro vai" /><BudgetLine label="Casa" value="R$ 1.840" width="72%" color="#e8a15a" /><BudgetLine label="Alimentação" value="R$ 1.120" width="54%" color="#9aa6db" /><BudgetLine label="Transporte" value="R$ 780" width="38%" color="#8ec0a7" /><BudgetLine label="Lazer" value="R$ 420" width="21%" color="#d5b4a0" /></section></div></div>; }
function Metric({ label, value, note, tone }: { label: string; value: string; note: string; tone: string }) { return <div className={`metric ${tone}`}><small>{label}</small><strong>{value}</strong><span>{note}</span></div>; }
function BudgetLine({ label, value, width, color }: { label: string; value: string; width: string; color: string }) { return <div className="budget-line"><div><span>{label}</span><strong>{value}</strong></div><i><b style={{ width, background: color }} /></i></div>; }
function MealsView({ setView }: { setView: (view: View) => void }) { return <div className="meal-grid"><section className="panel meal-plan"><PanelHeading eyebrow="SEMANA DE 31 AGO — 06 SET" title="Cardápio da família" action="Editar semana" /><div className="meal-days">{[['SEG','Frango assado','Arroz + salada'],['TER','Macarrão','Molho de tomate'],['QUA','Peixe grelhado','Purê de batata'],['QUI','Panquecas','Carne moída'],['SEX','Pizza caseira','Legumes']].map(([d, main, sub]) => <div className="meal-day" key={d}><small>{d}</small><strong>{main}</strong><span>{sub}</span></div>)}</div><button className="dark-button" onClick={() => setView('Listas')}>Adicionar ingredientes à lista</button></section><section className="panel recipe-card"><p className="eyebrow">RECEITA DA SEMANA</p><h2>Frango assado da casa</h2><p>Uma receita simples para deixar a quinta-feira mais leve.</p><div className="recipe-meta"><span>⏱ 45 min</span><span>♧ 5 porções</span></div><button className="outline-button">Ver receita completa →</button></section></div>; }
function SimpleCards({ type, flash }: { type: 'docs'; flash: (text: string) => void }) { const docs = [['🏠','Contrato de aluguel','Atualizado há 2 dias','PDF'],['🩺','Carteirinha do plano de saúde','Atualizado há 1 mês','PDF'],['🚗','Documento do carro','Atualizado há 3 meses','PDF']]; return <div className="cards-grid">{docs.map(([icon, title, date, kind]) => <button className="document-card" key={title} onClick={() => flash(`${title} selecionado`)}><span className="doc-icon">{icon}</span><strong>{title}</strong><small>{date} · {kind}</small><span className="card-arrow">↗</span></button>)}<button className="new-list-card" onClick={() => flash('Upload iniciado')}><span>＋</span><strong>Adicionar documento</strong><small>Arquivos seguros da família</small></button></div>; }
function MessagesView({ composer, setComposer, flash }: { composer: string; setComposer: (value: string) => void; flash: (text: string) => void }) { return <div className="messages-layout"><section className="panel chat-card"><div className="chat-head"><span className="member-avatar" style={{ background: '#30473e' }}>⌂</span><div><strong>Casa Oliveira</strong><small>3 membros · conversa da família</small></div></div><div className="messages"><div className="message other"><small>Ana · 08:10</small>Bom dia! Alguém consegue buscar o Pedro hoje?</div><div className="message mine"><small>Você · 08:14</small>Eu busco depois da natação. Já coloquei na agenda ✦</div><div className="message other"><small>Ana · 08:17</small>Perfeito, obrigada ❤️</div></div><div className="message-input"><input value={composer} onChange={(e) => setComposer(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && (flash('Mensagem enviada'), setComposer(''))} placeholder="Escreva uma mensagem..." /><button onClick={() => { flash('Mensagem enviada'); setComposer(''); }}>Enviar</button></div></section><section className="panel"><p className="eyebrow">LEMBRETES FIXADOS</p><h2>Para não esquecer</h2><div className="pinned"><span>⌁</span><div><strong>Comprar presente da vó</strong><small>Sábado · Ana</small></div></div><div className="pinned"><span>⌁</span><div><strong>Renovar seguro do carro</strong><small>15 de setembro · Você</small></div></div></section></div>; }
function LocationView({ flash }: { flash: (text: string) => void }) { return <div className="location-layout"><section className="map-card"><div className="map-orbit orbit-one" /><div className="map-orbit orbit-two" /><span className="map-pin pin-home">⌂</span><span className="map-pin pin-pedro">PE</span><span className="map-pin pin-ana">AN</span><div className="map-label home-label">Casa Oliveira <small>agora</small></div><div className="map-label school-label">Escola Monteiro <small>Pedro · há 12 min</small></div><div className="map-label ana-label">Ana <small>compartilhando</small></div></section><section className="panel location-side"><p className="eyebrow">LOCALIZAÇÃO COMPARTILHADA</p><h2>Somente quando você quiser.</h2><p className="body-copy">A localização está ativa para Ana e Pedro durante o horário combinado.</p><div className="location-person"><span className="member-avatar" style={{ background: '#9aa6db' }}>AN</span><div><strong>Ana</strong><small>Compartilhando até 21:00</small></div><button onClick={() => flash('Localização de Ana pausada')}>Pausar</button></div><div className="location-person"><span className="member-avatar" style={{ background: '#8ec0a7' }}>PE</span><div><strong>Pedro</strong><small>Autorização responsável ativa</small></div><button onClick={() => flash('Localização de Pedro pausada')}>Pausar</button></div><button className="outline-button" onClick={() => flash('Configurações de privacidade abertas')}>Gerenciar privacidade</button></section></div>; }
function RoutinesView({ flash }: { flash: (text: string) => void }) { return <div className="routine-grid">{[['☀','Manhã do Pedro','07:00 — 08:00',['Escovar os dentes','Tomar café','Separar mochila']],['🐾','Amora','Todos os dias',['Ração às 08:00','Passeio às 18:00','Remédio · domingo']],['🌙','Noite da casa','20:00 — 21:30',['Jantar sem telas','Preparar o dia seguinte','Luzes apagadas']]].map(([icon, title, time, items]) => <section className="panel routine-card" key={title as string}><span className="routine-icon">{icon}</span><p className="eyebrow">ROTINA</p><h2>{title as string}</h2><small>{time as string}</small>{(items as string[]).map((item) => <label key={item}><input type="checkbox" onChange={() => flash('Rotina atualizada')} />{item}</label>)}<button className="text-button">Editar rotina →</button></section>)}</div>; }
function BirthdaysView() { return <div className="birthday-grid"><Birthday month="SETEMBRO" items={[['02','Vó Helena','72 anos','#e8a15a'],['18','Ana','36 anos','#9aa6db']]} /><Birthday month="OUTUBRO" items={[['07','Pedro','10 anos','#8ec0a7'],['24','Carlos','39 anos','#d9a18d']]} /><section className="new-list-card birthday-add"><span>＋</span><strong>Adicionar aniversário</strong><small>Importe contatos ou cadastre uma data</small></section></div>; }
function Birthday({ month, items }: { month: string; items: string[][] }) { return <section className="panel birthday-card"><p className="eyebrow">{month}</p>{items.map(([day, name, age, color]) => <div className="birthday-row" key={name}><strong>{day}</strong><span className="birthday-avatar" style={{ background: color }}>{name.slice(0, 1)}</span><div><b>{name}</b><small>{age}</small></div><span className="birthday-gift">♢</span></div>)}</section>; }
function FamilyView({ flash }: { flash: (text: string) => void }) { return <div className="family-view"><section className="panel family-hero"><div className="family-large-icon">⌂</div><div><p className="eyebrow">FAMÍLIA ATIVA</p><h2>Casa Oliveira</h2><p>3 membros · criada em agosto de 2026</p></div><button className="outline-button" onClick={() => flash('Link de convite copiado')}>＋ Convidar família</button></section><section className="panel members-table"><PanelHeading eyebrow="MEMBROS E PERMISSÕES" title="Quem pode fazer o quê" /><div className="member-table-head"><span>PESSOA</span><span>PERFIL</span><span>ACESSO</span><span /></div>{members.map((m) => <div className="member-table-row" key={m.name}><span className="member-cell"><span className="member-avatar" style={{ background: m.color }}>{m.initials}</span><b>{m.name}</b></span><span>{m.role}</span><span className="access-pill">Calendário · Tarefas · Listas</span><button className="more-button" onClick={() => flash(`Permissões de ${m.name}`)}>•••</button></div>)}</section></div>; }
function NotificationsView() { return <div className="notification-list"><Notice icon="⌁" title="Natação do Pedro começa em 1 hora" time="há 12 min" tone="peach" /><Notice icon="✉" title="Ana aceitou o convite da família" time="há 2 h" tone="mint" /><Notice icon="◔" title="A conta de internet vence amanhã" time="ontem" tone="lavender" /><Notice icon="✓" title="Pedro concluiu: Separar uniforme da escola" time="ontem" tone="mint" /></div>; }
function Notice({ icon, title, time, tone }: { icon: string; title: string; time: string; tone: string }) { return <div className={`panel notice-row ${tone}`}><span className="notice-icon">{icon}</span><div><strong>{title}</strong><small>{time}</small></div><button className="more-button">•••</button></div>; }
function AssistantView({ text, setText, preview, setPreview, flash }: { text: string; setText: (value: string) => void; preview: string; setPreview: (value: string) => void; flash: (text: string) => void }) { return <div className="assistant-layout"><section className="panel assistant-chat"><div className="assistant-welcome"><div className="assistant-orb">✦</div><div><p className="eyebrow">NINHO INTELIGENTE</p><h2>Como posso aliviar sua semana?</h2><p>Eu consulto somente o que você permite e sempre mostro uma prévia antes de criar ou alterar algo.</p></div></div><div className="suggestions"><button onClick={() => setText('Organize as tarefas da casa entre mim e a Ana')}>Dividir tarefas da casa</button><button onClick={() => setText('Quais contas vencem nesta semana?')}>Contas da semana</button><button onClick={() => setText('Crie uma lista para o churrasco de sábado')}>Lista para o churrasco</button></div><div className="assistant-input"><input value={text} onChange={(e) => setText(e.target.value)} placeholder="Escreva um pedido para o Ninho..." /><button onClick={() => setPreview(text ? `Vou preparar uma prévia para: “${text}”` : 'Escreva um pedido primeiro.')}>Interpretar</button></div>{preview && <div className="preview-box"><span>✦</span><div><strong>Prévia da ação</strong><p>{preview}</p><small>Nada será alterado sem sua confirmação.</small></div><div className="preview-actions"><button className="outline-button" onClick={() => setPreview('')}>Editar</button><button className="dark-button" onClick={() => { flash('Ação confirmada e registrada'); setPreview(''); setText(''); }}>Confirmar ação</button></div></div>}</section><section className="panel tool-list"><p className="eyebrow">FERRAMENTAS CONTROLADAS</p><h2>O Ninho pode ajudar com</h2>{['Consultar agenda', 'Criar evento', 'Adicionar tarefa', 'Criar lista', 'Consultar orçamento', 'Encontrar disponibilidade'].map((tool) => <div key={tool}><span>✓</span>{tool}</div>)}</section></div>; }
function SettingsView({ flash }: { flash: (text: string) => void }) { return <div className="settings-grid"><section className="panel settings-card"><p className="eyebrow">PREFERÊNCIAS</p><Setting label="Lembretes de compromissos" detail="Receba avisos 30 minutos antes" /><Setting label="Resumo diário" detail="Todos os dias às 07:30" /><Setting label="Modo offline" detail="Salvar agenda e tarefas neste aparelho" /><Setting label="Biometria" detail="Proteger o Ninho com Face ID ou digital" /></section><section className="panel subscription-card"><p className="eyebrow">PLANO DA FAMÍLIA</p><span className="premium-badge">NINHO PREMIUM</span><h2>Mais leveza para famílias maiores.</h2><p>Documentos, orçamento completo, assistente inteligente e histórico estendido.</p><strong>R$ 24,90 <small>/ mês</small></strong><button className="dark-button full" onClick={() => flash('Checkout da assinatura aberto')}>Gerenciar assinatura</button></section><section className="panel danger-card"><p className="eyebrow">PRIVACIDADE E DADOS</p><button onClick={() => flash('Exportação preparada')}>Solicitar meus dados →</button><button onClick={() => flash('Configuração de exclusão aberta')}>Excluir minha conta →</button></section></div>; }
function Setting({ label, detail }: { label: string; detail: string }) { return <label className="setting-row"><span><strong>{label}</strong><small>{detail}</small></span><input type="checkbox" defaultChecked /></label>; }
